
export default {
    SET_SINGER : 'SET_SINGER',

    SET_PLAYING_STATE : 'SET_PLAYING_STATE',
    SET_FULL_SCREEN : 'SET_FULL_SCREEN',
    SET_PLAYLIST : 'SET_PLAYLIST',
    SET_SEQUENCE_LIST : 'SET_SEQUENCE_LIST',
    SET_PLAY_MODE : 'SET_PLAY_MODE',
    SET_CURRENT_INDEX : 'SET_CURRENT_INDEX',

    SET_DISC : 'SET_DISC',

    SET_TOP_LIST : 'SET_TOP_LIST',

    SET_SEARCH_HISTORY : 'SET_SEARCH_HISTORY',

    SET_PLAY_HISTORY : 'SET_PLAY_HISTORY',

    SET_FAVORITE_LIST : 'SET_FAVORITE_LIST',

}